### ISSUE TITLE
Comprar a comida

### ISSUE THREAD

**Issue by mirkolamberti** [mirkolamberti/scrum-kanban-churrasco#3]
**Compra de comida**

O fato de não ter restrições de budget, não significa gastar dinheiro a toa. 
Vamos verificar quais supermercados tem os melhores preços e qualidade e depois disso comprar onde tem mais conveniência pelas coisas que precisam.

**Comment by Joao-01** [comment]
Show! Dei uma volta nos principais Atacados da região e, pelo visto, não tem muita diferença de preços.
Tem uns com dia de promoção das verduras. Vou eperar para comprar.
Para a carne, dá para comprar no Supermercado Apertadão pelo fato de ter desconto na quantidade.

**Comment by mirkolamberti** [comment]
Ótimo @Joao-01. Então já que vai ser bastante carne, estava pensando aqui se dá para pedir a entrega direto no local. o Apertadão não lembro se tem esta opção.

Coloco o card em Fazendo, já que vc está na ativa neste ponto ;-)

**Comment by Vict-01** [comment]
@mirkolamberti @Joao-01 o Apertadão não trabalha com entregas. 
Veja se tem um frete barato para levar lá. Se não tiver posso chamar meu primo que tem carro com caçamba e pode nos ajudar.

**Comment by Joao-01** [comment]
Verdade. Lembrei agora. Então tá @Vict-01 vou chamar um frete e resolvo. Não precisa incomodar seu primo. Obrigado!

**Comment by mirkolamberti** [comment]
Pronto, então vou anotar aqui que a comida vai direto para o local. 
Isso significa que a preparação será feita lá!

**Comment by Joao-01** [comment]
COMIDA COMPRADA e já enviada para o local.
Fecho esta card.

**Comment by mirkolamberti** [comment]
Conferindo... tudo ok ;-)
Vou volocar o card na coluna Done.
