### ISSUE TITLE
Levar as coisas no local

### ISSUE THREAD

**Issue by mirkolamberti** [mirkolamberti/scrum-kanban-churrasco#4]
Após conferir compras e ferramentas, levar tudo até o local.

@Joao-01, veja se dá para colocar um adesivo nas nossas ferramentas, para não confundir com as que estão lá.
Se não der, pelo menos tira uma foto para depois reconhecer ;-)

**Comment by Joao-01** [comment]
Esta card podemos considerá-la resolvida. 
Todas as coisas vão direto para o local via frete. 

@mirkolamberti o que vc acha?

**Comment by mirkolamberti** [comment]
@Joao-01 sim. Fecho direto. Obrigado.
