### ISSUE TITLE
Preparar entradas

### ISSUE THREAD

**Issue by mirkolamberti** [mirkolamberti/scrum-kanban-churrasco#5]
Preparação entradas.

As verduras recheadas, podem ser preparadas antes e colocadas na geladeira.
Arroz, farofa e macaxeira serão preparados na manhã antes do começo do evento.

**Comment by mirkolamberti** [comment]
ATUALIZAÇÃO: @Joao-01 vai levar as comidas direto no local após ter comprado no Supermercado.
Então lembrem-se de ir pra lá um dia antes do evento para preparar tudo!

Vou colocar este card em A Fazer!

**Comment by Vict-01** [comment]
As entradas são comigo. Verduras e outras coisas é especialidade da minha família desde antes da descoberta do Portugal kkk.

**Comment by mirkolamberti** [comment]
Ótimo trabalho @Vict-01 
Entradas muito boas! Parabéns! Se estiver tudo certo, pode fechar a Issue ;-)

**Comment by Vict-01** [comment]
Pronto, posso fechar. Acabei de preparar tudo e colocar na geladeira.

**Comment by mirkolamberti** [comment]
Perfeito. Então fico na sua palavra. Coloco o card em Done.
