### ISSUE TITLE
Temperar carne

### ISSUE THREAD

**Issue by mirkolamberti** [mirkolamberti/scrum-kanban-churrasco#6]
Temperar carne

O tempero é sal e chimichurri, bem simples para deixar mais saborosa a carne.
Usar pouco sal para não ter problemas com o público com pressão alta.

**Comment by Joao-01** [comment]
Eu vou temperar as carnes! Tenho experiência pois em casa é tradição estudar o tempero perfeito desde meu tataravó rsrs.

**Comment by mirkolamberti** [comment]
Show @Joao-01, então vou colocar o card em **Fazendo**.

**Comment by mirkolamberti** [comment]
@Joao-01, tudo certo? Está precisando de ajuda para temperar as carnes?

**Comment by Joao-01** [comment]
Tudo tranquilo. So o javali que está dando um pouco de trabalho pois a carne foi tão fresquinha que praticamente entregaram ele vivo. Precisei limpar tudo e ainda amaciar com algumas cacetadas das minhas kkk.

**Comment by Vict-01** [comment]
> Tudo tranquilo. So o javali que está dando um pouco de trabalho pois a carne foi tão fresquinha que praticamente entregaram ele vivo. Precisei limpar tudo e ainda amaciar com algumas cacetadas das minhas kkk.

hahaha não sabia que suas cacetadas funcionavam como amaciante para carne.

**Comment by Joao-01** [comment]
kkk @Vict-01 só para carnes especiais kkk

Pronto, terminei. Posso fechar a Issue
