### ISSUE TITLE
Bebidas na geladeira

### ISSUE THREAD

**Issue by mirkolamberti** [mirkolamberti/scrum-kanban-churrasco#7]
Bebidas na geladeira.

As bebidas precisam ser colocadas na geladeira quanto antes. A gente pode colocar nas nossas até o momento de transferir tudo para o local.

@Vict-01, veja se cabe tudo nas nossas geladeiras, se não organiza uma primeira viagem para já colocar as bebidas em salvo!

**Comment by Vict-01** [comment]
Opa, vi aqui que temos poucas geladeiras. Vou aproveitar do frete que @Joao-01 vai usar para a comida para colocar as bebidas já no lugar.

**Comment by Vict-01** [comment]
@mirkolamberti escrevi uma lista das bebidas com o número de litros calculado.
Parece que o povo vai tomar banho na cerveja e depois agua e suco.
Veja se falta alguma coisa.

**Comment by mirkolamberti** [comment]
Opa @Vict-01, vi que colocou distilados. Ótimo. Já pensou na água de coco? O público muitas vezes corta o whiskey com água de coco e gelo.

Coloca também gelo, entre comida e bebida, não quero que fique esquecido rsrsrs

**Comment by Vict-01** [comment]
@mirkolamberti carambola, verdade!
Vou atualizar já já o arquivo.

**Comment by mirkolamberti** [comment]
Show! Deu certo? Não vi a atualização.

**Comment by Vict-01** [comment]
Opa, é porque não coloquei a referência no comentário. Vou atualizar.

**Comment by Vict-01** [comment]
Pronto @mirkolamberti aqui está.

**Comment by mirkolamberti** [comment]
Ótimo! Vamos que vamos.

**Comment by Vict-01** [comment]
BEBIDAS COPRADAS E ENTREGUE.
Terminei agora de colocá-las na geladeira.
Fecho o card.

**Comment by mirkolamberti** [comment]
Conferi e está tudo ok.
Falta uma garrafa de cerveja, mas é porque caiu, não porque eu tomei, viu!?!

Coloco o card em Done

**Comment by Joao-01** [comment]
> Conferi e está tudo ok. Falta uma garrafa de cerveja, mas é porque caiu, não porque eu tomei, viu!?!
> 
> Coloco o card em Done

Hum, entendi. Melhor "deixar cair" a fila toda para não deixar suspeitas kkkk
