### ISSUE TITLE
Checklist pronto

### ISSUE THREAD

**Issue by mirkolamberti** [mirkolamberti/scrum-kanban-churrasco#8]
Deixar tudo pronto.

Última conferida para saber se falta alguma coisa.

**Comment by mirkolamberti** [comment]
Ótimo pessoal. Então parece que foi feito tudo. 
Checklist aqui para conferir:

- [x] Comprar comida
- [x] Temperar carne
- [x] Preparar entradas
- [x] Gelar as bebidas

Tudo certo?

**Comment by Joao-01** [comment]
Sim, compras de carne e tempero pra mim é tudo ok.

**Comment by Vict-01** [comment]
Pra mim também. Fiz as entradas e tudo certo as outras coisas. 
Até dei uma última conferida no local, está tudo ok.

**Comment by mirkolamberti** [comment]
Ótimo pessoal, então dá para fechar essa última issue e fazer o commit do branch no main.
